### ISSUE TITLE
expanding a view breaks help modals

### ISSUE THREAD

**Issue by jmorrph** [ild-thl/moodle-block_disealytics#27]
After expanding a view (viewing the details) and returning to the main view only the help modal (`?`) of the just expanded view works

Steps:
1. view the dashboard, view details of a view
2. navigate back to the main view
3. try to open a help modal (klick the `?`) of a view other than the just expanded one
4. observe the modal NOT opening

**Comment by jmorrph** [comment]
tagging @alominty

**Comment by alominty** [comment]
working on this on branch #26
